In [50]:
# Indexing
import numpy as np
magic_sq = np.array([
    [16, 3, 2, 13],
    [5, 10, 11, 8],
    [9, 6, 7, 12],
    [4, 15, 14, 1]
])
print("second row:", magic_sq[1])
print("second col:", magic_sq[:, 1])
print("inner sq:", magic_sq[1:3, 1:3])

for i in range(4):
    assert magic_sq[i, :].sum() == 34
    assert magic_sq[:, i].sum() == 34

assert magic_sq[:2, :2].sum() == 34 # Quadrant 2
assert magic_sq[2:, :2].sum() == 34 # Quadrant 1
assert magic_sq[:2, 2:].sum() == 34 # Quadrant 3
assert magic_sq[2:, 2:].sum() == 34 # Quadrant 4

second row: [ 5 10 11  8]
second col: [ 3 10  6 15]
inner sq: [[10 11]
 [ 6  7]]


In [51]:
# masking
numbers = np.linspace(3, 60, 20, dtype=int).reshape(4, -1)
nums = np.arange(3, 61, 3).reshape(4, -1)
assert np.array_equal(numbers, nums)
print(numbers)

factors_of_3and4 = numbers[numbers % 4 == 0]
print(factors_of_3and4)


[[ 3  6  9 12 15]
 [18 21 24 27 30]
 [33 36 39 42 45]
 [48 51 54 57 60]]
[12 24 36 48 60]


In [60]:
# normal distribution
values = np.random.default_rng().standard_normal(100)
print(values[:3], "...", values[-3:])
std = values.std()
print("standard deviation: %.5f" %(std))

within_2sds = (values > -2 * std) & (values < 2 * std)
insiders = values[within_2sds]
outsiders = values[within_2sds == False]
print("Within 2 SDs: %.3f%%" %(insiders.size / values.size* 100))
print("Ousiders:", outsiders)



[1.34939678 1.56866812 0.06108002] ... [-2.16604541 -0.88430104  0.3547232 ]
standard deviation: 1.03608
Within 2 SDs: 94.000%
Ousiders: [ 2.68902941 -2.24174006  2.08869168  2.29095366  2.13439143 -2.16604541]


In [81]:
# Concatenating, Sorting
arrA = np.array([[1, 2], [3, 4]])
arrB = np.array([[5, 6], [7, 8]])

AB = np.concatenate((arrB, arrA)) # default vstack
AB_v = np.vstack((arrB, arrA))
AB_h = np.hstack((arrB, arrA))
print("vertical stack:\n", AB_v , "(default for np.concatente))")
print("horizontal stack:\n", AB_h)

# 각 단위 리스트별로 정렬 됨
print("vstack sort:\n", np.sort(AB_v))
print("hstack sort:\n", np.sort(AB_h))

lstack = np.concatenate((arrA, arrB), axis = None)
print("linear stack sort:\n", lstack)

vertical stack:
 [[5 6]
 [7 8]
 [1 2]
 [3 4]] (default for np.concatente))
horizontal stack:
 [[5 6 1 2]
 [7 8 3 4]]
vstack sort:
 [[5 6]
 [7 8]
 [1 2]
 [3 4]]
hstack sort:
 [[1 2 5 6]
 [3 4 7 8]]
linear stack sort:
 [1 2 3 4 5 6 7 8]
